app:
  env: "dev"

logging:
  stdout: true
  level: "debug"

scheduler:
  name: "smallest-fitting-edge-node"
  namespace: "smallest-edge-node-first"
  algorithm: "random"
  informerSyncPeriod: "15s"

connector:
  mode: "outside"
  masterURL: "172.20.2.4"
  kubeConfigPath: "/home/yashio/.kube/config"

cluster:
  edgeNodes: [ "k3d-ecmus-agent-0", "k3d-ecmus-agent-1", "k3d-ecmus-agent-2" ]
  masterNode: "k3d-ecmus-server-0"
